version: '2'
services:

  web:
    build: .
    ports:
      - "127.0.0.1:3001:80"

    depends_on:
      - "pg"
    entrypoint: ["./wait-for-postgres.sh", "pg", "/entrypoint.d/entrypoint.sh"]
    command: ["apache2-foreground"]

    environment:
     TOBA_ID_DESARROLLADOR: XXX
     TOBA_PASS: toba
    
    volumes:
     - ./src/gestion:/var/local/gestion

    extra_hosts:
     - "scc-test.unq.edu.ar:192.168.0.130"

    networks:
     default:
      aliases:
       - webg3

  pg:
    image: postgres:9.6
    command: postgres -c bytea_output=escape -c standard_conforming_strings=off
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5435:5432"
