version: '2'
services:

  web:
    build: .
    #image: siutoba/docker-guarani
    ports:
      - "127.0.0.1:3000:80"

    depends_on:
      - "pg"
    entrypoint: ["./wait-for-postgres.sh", "pg", "/entrypoint.d/entrypoint.sh"]
    command: ["apache2-foreground"]

    links:
     - pg
     - mailhog
     - jasper

    environment:
     TOBA_ID_DESARROLLADOR: 231
     TOBA_PASS: toba
     # Descomentar esta variable de entorno para corregir permisos en OSX
  #   OSX: 1
    volumes:
     - ~/devel-guarani/gestion:/var/local/gestion
     - ~/devel-guarani/docker-data/gestion/instalacion:/var/local/gestion/lib/toba/instalacion
     - ~/devel-guarani/autogestion:/var/local/autogestion
     - ~/devel-guarani/preinscripcion:/var/local/preinscripcion

    extra_hosts:
     - "campusextension.dev:172.17.0.1"
     - "qws.dev:172.17.0.1"

  # Descomentar este bloque si se desea utilizar el servidor Jasper
  jasper:
    build: jasper/
    # image: siutoba/docker-guarani-jasper
    links:
     - pg
    volumes:
     - ~/devel-guarani/gestion:/var/local/gestion
     - ~/devel-guarani/autogestion:/var/local/autogestion

  pg:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ~/devel-guarani/docker-data/pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432"
    command: "-c bytea_output=escape -c standard_conforming_strings=off"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "127.0.0.1:8026:8026"
    environment:
      - MH_SMTP_BIND_ADDR=0.0.0.0:25
      - MH_UI_BIND_ADDR=0.0.0.0:8026
      - MH_API_BIND_ADDR=0.0.0.0:8026
