version: '2'
services:

  web:
    build: .
    ports:
      - "127.0.0.1:3000:80"

    depends_on:
      - "pg"
    entrypoint: ["./wait-for-postgres.sh", "pg", "/entrypoint.d/entrypoint.sh"]
    command: ["apache2-foreground"]

    environment:
     TOBA_ID_DESARROLLADOR: XXX
     TOBA_PASS: toba
     TOBA_DIR: /var/local/gestion/vendor/siu-toba/framework
     TOBA_INSTALACION_DIR: /var/local/gestion/instalacion

    volumes:
     - ~/devel-guarani/gestion:/var/local/gestion
     - ~/devel-guarani/autogestion:/var/local/autogestion
     - ~/devel-guarani/preinscripcion:/var/local/preinscripcion

    extra_hosts:
     - "scc-test.unq.edu.ar:192.168.0.130"
    networks:
     default:
      aliases:
       - webg3

  jasper:
     build: jasper/
     volumes:
       - ~/devel-guarani/gestion:/var/local/gestion
       - ~/devel-guarani/autogestion:/var/local/autogestion
  
  pg:
    image: postgres:11.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ~/devel-guarani/docker-data/pgdata:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5434:5432"
    command: "-c bytea_output=escape -c standard_conforming_strings=off -c timezone=America/Argentina/Buenos_Aires -c log_timezone=America/Argentina/Buenos_Aires"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "127.0.0.1:8026:8026"
    environment:
      - MH_SMTP_BIND_ADDR=0.0.0.0:1025
      - MH_UI_BIND_ADDR=0.0.0.0:8026
      - MH_API_BIND_ADDR=0.0.0.0:8026

#hay que correr por unica vez
#docker network create uvq_net
networks:
  default:
    external:
      name: uvq_net
